// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBatiutuIPd94njsddan0vWxn-Kk-hqYiE',
    appId: '1:53679447657:web:6f076865d20a9cd828ccf8',
    messagingSenderId: '53679447657',
    projectId: 'plantdoctor-34d9d',
    authDomain: 'plantdoctor-34d9d.firebaseapp.com',
    storageBucket: 'plantdoctor-34d9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA98wdGHdLsxuRoOgIsAbvZr3p6NBFC_No',
    appId: '1:53679447657:android:930307589d2a7a3228ccf8',
    messagingSenderId: '53679447657',
    projectId: 'plantdoctor-34d9d',
    storageBucket: 'plantdoctor-34d9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCokLQxEJRqS_VkZWjp2sfs5FJX7rYDojI',
    appId: '1:53679447657:ios:9a907dd5864480ae28ccf8',
    messagingSenderId: '53679447657',
    projectId: 'plantdoctor-34d9d',
    storageBucket: 'plantdoctor-34d9d.firebasestorage.app',
    iosBundleId: 'com.example.plantDoctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCokLQxEJRqS_VkZWjp2sfs5FJX7rYDojI',
    appId: '1:53679447657:ios:9a907dd5864480ae28ccf8',
    messagingSenderId: '53679447657',
    projectId: 'plantdoctor-34d9d',
    storageBucket: 'plantdoctor-34d9d.firebasestorage.app',
    iosBundleId: 'com.example.plantDoctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBatiutuIPd94njsddan0vWxn-Kk-hqYiE',
    appId: '1:53679447657:web:30d387304d876d2428ccf8',
    messagingSenderId: '53679447657',
    projectId: 'plantdoctor-34d9d',
    authDomain: 'plantdoctor-34d9d.firebaseapp.com',
    storageBucket: 'plantdoctor-34d9d.firebasestorage.app',
  );
}
